version: '2'
services:
  web:
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    volumes:
      - ".:/magic_logger/"
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    expose:
      - "3000"
