# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cfc13c2b18b751dc925da2dd1c2bb63dd1835cbc0831e107ce07afa988f097bc8db800f3f90ee6b858154761bd0304a65e5b7afda50caa90975159fe8fe01c6
  elasticsearch_url: "http://elasticsearch:9200"
  dashboard_password: "123456"

test:
  secret_key_base: b56b9cab7d6e50f09387ff3d3a1282e8700ccda748fd4ca2b06043c80ecc229223f7f5ecbea00de25bf885fdada7c6de3d3d1e8e797cfe288e6ed3b866bbf720
  elasticsearch_url: "http://elasticsearch:9200"
  dashboard_password: "123456"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  elasticsearch_url: <%= ENV["ELASTICSEARCH_URL"] %>
  dashboard_password: <%= ENV["DASHBOARD_PASSWORD"] %>
