apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  type: LoadBalancer
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    name: elasticsearch
