apiVersion: v1
kind: Service
metadata:
  name: magic-logger
  labels:
    name: magic-logger
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: magic-logger
