apiVersion: v1
kind: Service
metadata:
  name: heroku-logger
  namespace: minestore-production
  labels:
    name: heroku-logger
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: heroku-logger
