apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heroku-logger
  labels:
    name: heroku-logger
spec:
  template:
    metadata:
      labels:
        name: heroku-logger
    spec:
      containers:
      - name: heroku-logger
        image: gcr.io/commonwealth-156613/heroku-logger:latest
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP
        env:
          - name: ELASTICSEARCH_URL
            valueFrom:
              secretKeyRef:
                name: heroku-logger-secrets
                key: elasticsearch_url
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: heroku-logger-secrets
                key: secret_key_base
          - name: DASHBOARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: heroku-logger-secrets
                key: dashboard_password
