apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    name: logstash
spec:
  type: LoadBalancer
  ports:
    - port: 9600
      targetPort: 9600
      protocol: TCP
  selector:
    name: logstash
